### ISSUE TITLE
Manca il caso 30 euro

### ISSUE THREAD

**Issue by stonks404** [mralko99/Meatballs#2]
Sbrigati

**Comment by AlessandroGaeta1** [comment]
Daje m pò

**Comment by desagab** [comment]
@mralko99 movite pure

**Comment by stonks404** [comment]
![Screenshot_20200814-224357_Chrome](https://user-images.githubusercontent.com/64980092/90291259-d0972280-de7f-11ea-86ac-8f605d112712.jpg)
